apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: walkme-backend-ingress
  namespace: walkme
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: walkme.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: walkme-backend
                port:
                  number: 80
